### ISSUE TITLE
Create Button Component

### ISSUE THREAD

**Issue by rotimidokun** [KanaryStack/aliascheck#5]
Buttons will be in two forms:

- Outline Button
- Solid Button

There should be no set width.
Use props to determine button type.
Define props type.

<img width="134" alt="image" src="https://user-images.githubusercontent.com/51387182/176026307-34978836-8b59-4fd8-a9ca-4af61f5cd37e.png">

<img width="414" alt="image" src="https://user-images.githubusercontent.com/51387182/176026355-e29f2a93-0116-4dd2-895c-065e64bd9a58.png">

<img width="133" alt="image" src="https://user-images.githubusercontent.com/51387182/176026430-a9773c2b-f0d9-4cc6-8727-108f3d4087e1.png">

**Comment by valentinesamuel** [comment]
Hi @rotimidokun and @simplytunde, I would like to take on this issue.

**Comment by rotimidokun** [comment]
@valentinesamuel This was a previous ticket that I doubt is relevant at the moment. 

We are currently working with a new design from our product designer which does not look like what we have here.

**Comment by rotimidokun** [comment]
@simplytunde @Maxwell-ihiaso  @RWambui  I will be going ahead to close this issue for the reason stated above.
